# Generated by Django 4.0.1 on 2022-05-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='surname',
        ),
    ]
